### ISSUE TITLE
Issue in the DELETE Request of HTTP2 plugin

### ISSUE THREAD

**Issue by anupam-nagarro** [Blazemeter/jmeter-http2-plugin#16]
Whenever the DELETE http method is selected the sampler doesn't take the body in the delete request instead it attaches the body to the URL as in the GET requests.
![image](https://user-images.githubusercontent.com/52594191/130596303-7b268a3f-6771-4814-9f7c-e5e9fa968338.png)
![image](https://user-images.githubusercontent.com/52594191/130596478-82722ec7-cb6b-4a39-a79a-9b30c36b0f7e.png)

**Comment by RicardoPoleo** [comment]
Hello @anupam-nagarro,

Thanks for taking the time to report this issue, and we apologize for any inconvenience this might generate.

Right now we are working on a major version, and we will add this to our backlog to fix it on that release. 

I'll go back to you when we make it so you can try it out.

Happy hacking!

**Comment by RicardoPoleo** [comment]
I'll be closing this issue. Feel free to reopen it if this behaviour persists on your end. 

In case another problem appears, feel free to create another issue for that one (not this one while is closed).

Hope you have a nice week
