### ISSUE TITLE
"File Upload" functionality is not working in Jmeter with HTTP2 sampler [with all versions of JMETER]

### ISSUE THREAD

**Issue by Maurya-Dheeru** [Blazemeter/jmeter-http2-plugin#20]
I am using "File Upload" option in the HTTP2 sampler to execute the load test with > 4.0 Jmeter version.

I have tried to "File Upload" option in the HTTP2 sampler and observed that the path provided for the "file path" getting removed when we move across the other samplers, therefore it's not possible to use the file upload option in the HTTP2 sampler.

Added data in File Upload
![image](https://user-images.githubusercontent.com/96529914/147093205-2e489114-3cf5-4b3a-ba55-c22cd726d49b.png)

Post moving to the another thread/sampler, "file path" got removed.
![image](https://user-images.githubusercontent.com/96529914/147093249-22379d47-4bfc-48d6-bed0-fb153a073c58.png)

Is there any another way to use in "file path" in HTTP2 sampler.

**Comment by RicardoPoleo** [comment]
Hello @Maurya-Dheeru,

Thanks for taking the time to document and report it. 

This is clearly a bug from our side, I'm sorry about it. We added this to our backlog and, when the release with the fix is made, I'll come back and let you know, so you can try it out.
