### ISSUE TITLE
Http2 sampler Idle timeout 30000 ms elapsed

### ISSUE THREAD

**Issue by ngoel2005** [Blazemeter/jmeter-http2-plugin#25]
Our requirement is to get response in HTTP/2.0. So we are using HTTP2 sampler plugin. Its working fine till the response time under 30 sec. 
If response time more than 30 sec than we are getting “Idle timeout 30000 ms elapsed”.
We have done all changes which are available in property files (Jmeter User, System).
Please suggest any work around.
[Plugin Requirement.docx](https://github.com/Blazemeter/jmeter-http2-plugin/files/8539736/Plugin.Requirement.docx)

**Comment by 3dgiordano** [comment]
Hi @ngoel2005 

We identified that jetty internally has a default timeout for connections waiting for a response.

In the next few days we will release a version that will allow you to configure this timeout.
When the version has been released, we will let you know.

Regards

**Comment by ngoel2005** [comment]
Hi
Thank you for your reply.
Any tentative time for release.


Thanks & Regards
Neeraj

**Comment by 3dgiordano** [comment]
Hi @ngoel2005 

Exist a pre-release if you need to test now
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.2

You need to set a jmeter property to configure the default maximum idle time out

**httpJettyClient.idleTimeout**                     : the max time, in milliseconds, a connection can be idle                                 

The final release we hope to have it to the public before the first of December

**Comment by ngoel2005** [comment]
Thanks for the update.

**Comment by 3dgiordano** [comment]
Hi @ngoel2005 
The final release 2.0.2 is here https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.2
In hours it will be available in Plugin Manager.

Now all the jmeter properties area documented here
https://github.com/Blazemeter/jmeter-http2-plugin#properties
Inside you can see the new property httpJettyClient.idleTimeout

We are waiting to see if it resolves your issues.

Regards

**Comment by RicardoPoleo** [comment]
Hello @ngoel2005,

It has been a while since we saw some activity regarding this issue. I'll be closing it but, if the error persists in the current version, please don't hesitate to open it up again.

**Comment by ngoel2005** [comment]
Thanks for the update.
