### ISSUE TITLE
Why use gzip by default?

### ISSUE THREAD

**Issue by jerviscui** [Blazemeter/jmeter-http2-plugin#26]
I see the Request Header has a `Accept-Encoding: gzip` by default.
And I can't delete the Accept-Encoding header.
Although I add a header `Accept-Encoding: none` ，but gzip will still take effect.

**Comment by 3dgiordano** [comment]
Hi @jerviscui and @Yurons 

I made a pre-release with some changes in the plugin.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.2

This pre-release solve the problem of `Accept-Encoding: gzip` and `User-Agent: Jetty/11.0.6`

Before its release, I need feedback on this version.
I await your feedback.
Thanks.

**Comment by jerviscui** [comment]
Thank you @3dgiordano 
I'll find a way to use it.

**Comment by 3dgiordano** [comment]
Hi @jerviscui 
The final release 2.0.2 is here https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.2
In hours it will be available in Plugin Manager.

We are waiting to see if it resolves your issues.

Regards

**Comment by RicardoPoleo** [comment]
Hello @jerviscui, @Yurons 

It has been a while since we saw some activity regarding this issue. I'll be closing it but, if the error persists in the current version, please don't hesitate to open it up again.
