### ISSUE TITLE
Retrieve all embedded resources parallel downloads handling for http2

### ISSUE THREAD

**Issue by serputko** [Blazemeter/jmeter-http2-plugin#40]
Hello all,
current http2 Retrieve all embedded resources implementation works similar to regular HttpRequest implementation and might be confusing for end users. It also requires a lot of time to figure out how plugin works under the hood to make it working as expected.

Here what I mean:
let's imagine simple case with simple html page and bunch of static resources in it, everything works on http2. 
As a user I create http2 sampler, configure it and enable "Retreive all embedded resources" and "Parallel downloads=6" as looks the same as for regular Http sampler.

From the first sight it works, but actually jmeter creates 7 tcp connections to server instead of 1 as per http2 spec. 
It also creates ([http.JettyClient.minThreads  ...  http.JettyClient.maxThreads] x 6) amount of threads to download static data.
![telegram-cloud-photo-size-2-5366512979123751973-w](https://user-images.githubusercontent.com/16308826/214211192-289c8c51-1f5e-428b-9a8e-19c11f37f8b6.jpg)
![telegram-cloud-photo-size-2-5366512979123751974-w](https://user-images.githubusercontent.com/16308826/214211213-079b735c-65af-4171-ad5c-9d39a3069fbf.jpg)
<img width="643" alt="image" src="https://user-images.githubusercontent.com/16308826/214211326-6d7e6c98-603d-4929-b2ca-ff9cac0a5eca.png">
Requests are sent in different connections(not expected):
<img width="253" alt="image" src="https://user-images.githubusercontent.com/16308826/214212639-79addd46-9e8e-45fe-b61b-851136373aa1.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/16308826/214212669-219d0340-0cbf-40f7-8e50-8b0fd86caecd.png">

That looks like an overhead from Jmeter perspective as well as it's not similar to how browser and other clients handle this. 
To make it realistic you should tick "Retreive all embedded resources" but do NOT tick "Parallel dowloads". In this case jmeter will create 1 tcp connection(as expected) and load resources in N threads you specify in jmeter properties [http.JettyClient.minThreads, http.JettyClient.maxThreads]
![telegram-cloud-photo-size-2-5366512979123751971-w](https://user-images.githubusercontent.com/16308826/214211366-b82b557a-a8b2-40e9-ac20-7edbcdff17ca.jpg)
![telegram-cloud-photo-size-2-5366512979123751972-w](https://user-images.githubusercontent.com/16308826/214211381-98fff262-45a3-493c-8057-bc9483f014e8.jpg)
Requests are also sent in single connection as expected:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/16308826/214212429-52015699-f57e-4047-978a-690cf1318557.png">
<img width="211" alt="image" src="https://user-images.githubusercontent.com/16308826/214212472-6eb0416f-05bb-4adb-9a7d-c42564ffca3a.png">

Let's document this behavior or warn users about this somehow in UI or remove that parallel download feature at all for http2 calls.

Thanks :)

**Comment by serputko** [comment]
@3dgiordano as requested
I've used http://www.http2demo.io/ as a demo site
it has both http1 and http2 resources 
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/16308826/214693790-71fd7080-1f4d-4ec9-a04f-55922b11272e.png">

jmx example:
please change .txt to .jmx as git is not alowing to upload jmx files
[bzm - HTTP2 Sampler.txt](https://github.com/Blazemeter/jmeter-http2-plugin/files/10503831/bzm.-.HTTP2.Sampler.txt)

Http2 plugin version: 
jmeter-bzm-http2-2.0.2

Java version: 
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Homebrew (build 11.0.16.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.16.1+0, mixed mode)

Thanks

**Comment by 3dgiordano** [comment]
Thanks @serputko

**Comment by 3dgiordano** [comment]
Hi @serputko

We finished carrying out the analysis of what you mentioned to us.
You are correct, the embedded resource download execution model is not correct and requires work.

Thank you very much for reporting the problem to us.
We will be working on solving the problem, which will be available in an upcoming release that we will carry out in the coming weeks.

Regards

**Comment by 3dgiordano** [comment]
Hi @serputko 

We made an initial support implementation of asynchronous execution in the plugin.
In this preview release, we fixed some problems of downloading embedded resources in parallel for http2.

You can download and test the pre-release version in alpha in the releases section
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.3-alpha

Let us know if it resolves what was reported in this issue.

**Comment by 3dgiordano** [comment]
Hi @serputko 

Final release of version 2.0.3 was done today.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.3

Soon it will be available in JMeter Plugins Manager.
