### ISSUE TITLE
new version of jetty available 11.0.14

### ISSUE THREAD

**Issue by heysarthak** [Blazemeter/jmeter-http2-plugin#57]
Hi Team,

http2 plugin is currently using jetty 11.0.10 which has some vulnerability, which has been cleared in 11.0.14 version of jetty. when are we planning to upgrade it?

Thanks

**Comment by 3dgiordano** [comment]
Hi @heysarthak 
  
Final release of version 2.0.3 was done today and that version uses jetty core 11.0.15.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.3

Soon it will be available in JMeter Plugins Manager.

Regards.
