### ISSUE TITLE
bzm - HTTP2 Async Controller - 2nd a subsequent Requests not made when in a Loop Controller.

### ISSUE THREAD

**Issue by Pill30** [Blazemeter/jmeter-http2-plugin#59]
Win11 Pro
JMeter 5.5
Java 11 and tried Java 19
HTTP/2 - jmeter-bzm-http2-2.0.3 (https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.3)

**Test**
Loop Controller * 2
bzm - HTTP2 Async Controller

- Sampler (GraphQL API Call) 

End Loop

**Result**
Even though the loop controller is 2, the Sampler request is only made once. This is not a caching issue. The problem isn't specific to GraphQL, it's just an example.
Note that if you don't use the 'bzm - HTTP2 Async Controller', the 2nd request is correctly made.

**NOTE:** - This does **NOT** occur on v2.0.3-alpha.3 (+jetty 11.0.10) https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.3-alpha.3

**Comment by 3dgiordano** [comment]
Hi @Pill30 

Could you provide a jmx file that allows us to reproduce the issue easily?

**Comment by Pill30** [comment]
@3dgiordano 
Testplan attached. (saved as .txt extension)
Right click on thread group and select Validate. Sampler request to github only made once even though loop is set to 2.

[http2-issue-2.0.3.jmx.txt](https://github.com/Blazemeter/jmeter-http2-plugin/files/12843747/http2-issue-2.0.3.jmx.txt)

Files Used:
![image](https://github.com/Blazemeter/jmeter-http2-plugin/assets/49448014/468974b3-7560-4567-bd69-55ffe777a90d)

**Comment by 3dgiordano** [comment]
Hi @Pill30 

Thank you very much for providing the example to understand what exactly was the case.

The problem it's the same problem reported on this issue
https://github.com/Blazemeter/jmeter-http2-plugin/issues/61

I'm working on it and I hope to make the solution available between today and tomorrow.

**Comment by 3dgiordano** [comment]
Hi @Pill30 

New release with fixes released.
You can access it from the Releases section on GitHub.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.5

It will be available in Plugin Manager in the next 24 hours.

Could you tell us if this version resolves the reported issue?

**Comment by Pill30** [comment]
Hi @3dgiordano,

Retested said jmx with:

- jmeter-bzm-http2-2.0.5.jar (https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.5)
- JMeter 5.5
- Java 11

It's now correctly making requests as per loop counter.
Thanks for your excellent work. Bravo.

**Comment by 3dgiordano** [comment]
Thank you @Pill30 for reporting the issue and also confirming its resolution.

I proceed to close the current issue.
If you have any new problem, do not hesitate to raise a new issue.

Regards
