### ISSUE TITLE
Infinite loop is not taken into account for HTTP2 Async Controller

### ISSUE THREAD

**Issue by baranskigl** [Blazemeter/jmeter-http2-plugin#61]
Hi,

I'm using JMeter 5.5 and newest plugin 2.0.3.
I try to create test plan with infinite loop (Thread Group setting) and thread lifetime duration 60s for bzm HTTP2 Async Controller.

It seems it is not working or maybe I misconfigured something.

![image](https://github.com/Blazemeter/jmeter-http2-plugin/assets/36693759/274027b0-c280-412b-ac9c-c6675db0ceb3)

It seems it's only one iteration happened.

![image](https://github.com/Blazemeter/jmeter-http2-plugin/assets/36693759/5137e85d-cb44-4e85-9c35-5d20d2e1b145)

Can you support here?
Thanks in advance, 
Bartosz

**Comment by 3dgiordano** [comment]
Hi @baranskigl 

We were able to reproduce the problem.
The problem occurs in both Thread Group and any other type of loop controller.

Thanks for reporting the issue.

**Comment by baranskigl** [comment]
Hi @3dgiordano,

thank you for your answer.

Do you plan to fix it soon?

/Bartosz

**Comment by 3dgiordano** [comment]
Hi @baranskigl 

Yes, I'm working in it.

It is possible that the fix to the problem will be available on GitHub today or tomorrow.

**Comment by 3dgiordano** [comment]
Hi @baranskigl

New release with fixes released.
You can access it from the Releases section on GitHub.
https://github.com/Blazemeter/jmeter-http2-plugin/releases/tag/v2.0.5

It will be available in Plugin Manager in the next 24 hours.

Could you tell us if this version resolves the reported issue?

**Comment by baranskigl** [comment]
Hi @3dgiordano,

thank you.

Sure, I will inform you if provided fix is fine today/tomorrow.

**Comment by 3dgiordano** [comment]
Hi @baranskigl 

Did you have a chance to try the new version?
Does the new version solve the problem reported in this issue?

**Comment by baranskigl** [comment]
Hi @3dgiordano,

sorry for delay. Yes, it works. Thank you.
